name: Eartha Major
favicon: null
layout_spectrum: 0.945101
typography_spectrum: 0.549831
title: Eartha Major
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D0C8B8'
    - '#000000'
    - '#787868'
    - '#000000'
    - '#000000'
  brandStrength: 0.960032
  lightness: 0.258446
  saturation: 0.94945
  rhythmicContrast: 0.880825
purpose:
  - name: null
    item: null
    url: null
